CONTRIBUTING.md

Hi all
Could you please review this pull request test?
All the best
Roberto

Remove empty line. Test Microsoft DevOps - GitHub integration AB#28637.

---

api/mapping/models.py
api/mapping/services.py

Fixed issue in ScanReportField model.

Update to ScanReportField model to handle blank classification system

---

api/mapping/templates/mapping/scanreportvalue_list.html
api/mapping/urls.py
api/mapping/views.py

This PR contains code that displays all the values from each field in the dataset.

Display values to corresponding fields

---

api/mapping/templates/mapping/scanreportvalue_list.html

This PR adds the frequency column in the scanreport_list.html file for each field value

Add frequency values to scanreportvalue_list.html

---

api/mapping/forms.py
api/templates/registration/password_change_form.html

This PR adds password validation to the password change form

Add password validation in password change form

---

api/mapping/templates/mapping/scanreportfield_list.html

I have added the data type of the source value for the scan report field list.

31411 add datatype to fields screen

---

api/static/style/custom.css

This PR includes:
- Change the colours of the buttons to be the same as the standard co-connect palette
- Remove hover up effect from navigation bar

Changes in CSS

---

api/mapping/templates/mapping/datadictionary_list.html
api/mapping/templates/mapping/scanreportfield_list.html
api/mapping/views.py
api/static/style/custom.css

UI updates to tables and buttons

---

api/mapping/models.py
api/mapping/templates/mapping/scanreportfield_list.html
api/mapping/views.py

Reverts CO-CONNECT/mapping-pipeline#59

Revert "Add conceptID in the ScanReportField model"

---

api/mapping/models.py
api/mapping/services.py
api/mapping/templates/mapping/scanreportfield_list.html

When the data team modifies the White Rabbit scan reports as depicted in the uploaded screenshot, they can include the classification system of each source field which can be incorporated into the site's scan report.

32420 import classification system from scan report

---

api/mapping/models.py
api/mapping/views.py

Adds pass_from_source back into ScanReportField model
Fixes Scan Report upload bug reported by Shameema Farvin.

Added pass_from_source back to SRField, fixed SR upload bug

---

api/mapping/views.py

This PR updates `update_or_create()` within StructuralMappingTableListView. By default, maps are now set to approved, as requested by PQ.

Mappings are now automatically approved

---

api/mapping/management/commands/insert_omop.py
api/mapping/models.py
api/mapping/views.py

Needs https://github.com/CO-CONNECT/co-connect-tools/pull/27

33534 update omop tables and fields

---

api/mapping/services.py
api/mapping/services_nlp.py
api/mapping/tasks.py
api/mapping/views.py

I've formatted views.py with isort and PEP8 (using Black).
I've started moving some of the NLP code to it's own services file. I will move more later, once views.py has been merged into master.

Formatting views.py, moving NLP code to services_nlp.py

---

api/mapping/forms.py
api/mapping/models.py
api/mapping/templates/mapping/document_list.html
api/mapping/templates/mapping/scanreport_list.html

Change the return from models.py so there is no issue with deleting model objects from the admin page.

change return string for models so they can be deleted from admin page

---

api/mapping/admin.py
api/mapping/models.py

This PR adds a new model for NLP conceptIDs

#AB34487 Added ScanReportConceptID model

---

api/mapping/services_nlp.py

Very small PR to fix two bugs in NLP
1. Fixed issue where string was coming from field_description and not description_column
2. Added try/except when looking up conceptIDs from concept codes. For now, puts in log that ID wasn't found.

Minor NLP bugfixes

---

docker/django/requirements.txt

Bump up django version to 3.1.12

[IMPORTANT] bump up django version (#141)

---

api/api/settings.py

PR to mask secret key. 
Key must now be kept in .env

Generated new secret key and masked it with os.environ

---

api/mapping/services_nlp.py
api/mapping/views.py

Small PR to add a message banner for NLP run (instead of a redirect to values).

Added messages to say NLP running (rather than a redirect)

---

api/mapping/services_rules.py
api/mapping/views.py

* Refresh Rules fails because of drug_exposure concepts that have been added. Now it failed to generate rules for already existing ones
* Stop non-allowed concepts from being added in the first place

Fix bug when adding concepts not in m_allowed_tables

---

.github/workflows/ci.yml
api/api/settings.py

Alter `AZURE_ACCOUNT_NAME`, `DEBUG` and `ALLOWED_HOSTS` environment variables from hard-coded in `settings.py` to being read from the environment.

Move out env vars to be read from environment

---

.github/workflows/ci.yml
Dockerfile.deploy
entrypoint.sh

this will avoid the 'rm cannot remove .' warnings.

Delete the whole of api/staticfiles/ and recreate the directory afresh

---

api/api/settings.py
api/requirements.txt

I got confirmation from Samuel Adejumo that CORS setup is working fine for him. This PR has CORS setup to be merged into devel branch.

Shahzad updates CORS setup

---

api/mapping/urls.py
api/mapping/views.py

Shahzad api updates 18 aug2021

---

changelog.md

The intention is that all future PRs that contain any notable changes should include an edit to changelog.md to note the changes.

Add changelog.md including all changes since v1.0.0 so far.

---

api/mapping/urls.py
api/mapping/views.py
changelog.md

Some changes have been made in the API endpoints in view of following requirements from Samuel Adejumo.
After making changes the documentation pack is also updated (though still require some cleaning and some explanations for the newly added endpoints.) 
Tests were conducted to make sure no previous functionality is affected.

Shahzad API Updates 02092021

---

api/mapping/templates/mapping/mappingrulesscanreport_list.html
api/mapping/views.py
changelog.md
react-client-app/package.json
react-client-app/src/App.jsx
react-client-app/src/api/values.js
react-client-app/src/components/FilterTag.jsx
react-client-app/src/components/MappingTbl.jsx
react-client-app/src/mappingRules.jsx

Add mapping rules page in React

---

ProcessQueue/__init__.py
api/mapping/serializers.py

This gets some way towards fixing identified issues with scan report uploads.

Pagination of Field uploads, and removal of whitespace trimming in serialisation of certain fields.

---

api/mapping/templates/mapping/scanreporttable_list.html
api/mapping/views.py
changelog.md
react-client-app/src/App.jsx
react-client-app/src/api/values.js
react-client-app/src/components/TablesTbl.jsx
react-client-app/src/tablesTable.jsx

Added react version of tables page to app

React tables page

---

ProcessQueue/__init__.py

Also extend max chars in a page to 10000 - this could do with being investigated for performance vs maximum limit.

Add pagination of values and concepts.

---

api/mapping/templates/mapping/scanreporttable_form.html
api/mapping/views.py
changelog.md
react-client-app/src/App.jsx
react-client-app/src/api/values.js
react-client-app/src/components/EditTable.jsx
react-client-app/src/editTable.jsx

React edit table

---

api/mapping/templates/mapping/scanreportfield_form.html
api/mapping/views.py
changelog.md
react-client-app/src/App.jsx
react-client-app/src/components/EditField.jsx
react-client-app/src/editField.jsx

Added edit field page to react app

React edit field

---

api/mapping/templates/mapping/mappingrulesscanreport_list.html
react-client-app/src/components/MappingTbl.jsx
react-client-app/src/styles.js

Added button to download diagram
Changed download mapping rules button to point at python implementation

Mapping rules download button

---

react-client-app/src/api/values.js
react-client-app/src/components/DataTbl.jsx

Change to getScanReports function in values.js to use batch call on omop concepts to improve speed
Change to handleSubmit function in DataTbl to add extra checks that that weren't previously implemented from django code to react version in values.

React values page

---

react-client-app/src/components/ScanReportTbl.jsx

added mappings column to scanreports table

---

react-client-app/src/App.jsx
react-client-app/src/api/values.js
react-client-app/src/components/ConceptTag.jsx
react-client-app/src/components/DataTbl.jsx
react-client-app/src/components/EditField.jsx
react-client-app/src/components/FieldsTbl.jsx
react-client-app/src/components/Home.jsx
react-client-app/src/components/MappingTbl.jsx
react-client-app/src/components/PageHeading.jsx
react-client-app/src/components/ScanReportTbl.jsx
react-client-app/src/components/TablesTbl.jsx

Added comments to the react code

React comments

---

api/mapping/templates/mapping/scanreporttable_list.html
api/mapping/templates/mapping/scanreportvalue_list.html
react-client-app/src/components/DataTbl.jsx
react-client-app/src/components/TablesTbl.jsx

Removed goto rules button in templates and added it to react code

Tables error fix

---

react-client-app/src/components/Home.jsx

Linked colours across graphs on the home page

added a function to generate colours for datapartners

---

react-client-app/src/components/Home.jsx

added bar chart to home

---

ProcessQueue/__init__.py

Finish when 2 empty rows are detected.

Add guard to stop processing of empty rows in scan report. 

---

react-client-app/package-lock.json
react-client-app/package.json

Updated all dependencies in the vulnorability list except "ansi-html" as there are no patched versions available

Vulnorability fixes

---

react-client-app/src/components/ScanReportTbl.jsx

removed current user check on scan reports to be able to archive

removed current user check

---

react-client-app/src/components/MappingTbl.jsx

Added concept name to term mapping in table

Mapping tbl

---

react-client-app/src/components/MappingModal.jsx
react-client-app/src/components/MappingTbl.jsx
react-client-app/src/components/RulesTbl.jsx
react-client-app/src/components/SummaryTbl.jsx

Added button to open summary view in mapping rules

Summary tbl

---

ProcessQueue/__init__.py

A rewrite of the functionality for data dictionaries. Split the incoming data into rows that contain a non-empty `code` field and those which do not. The former are value descriptions, the latter are possible vocabularies for a field. Use each in the correct manner.
Additionally, format the dictionaries as nested dicts for fast access rather than lists of tuples.

Better dict handling

---

api/api/settings.py
changelog.md

Change the session length to 24 hours

Change session length to 24 hours

---

api/mapping/models.py
api/mapping/services_rules.py
changelog.md
react-client-app/src/App.jsx
react-client-app/src/api/values.js
react-client-app/src/components/ConceptTag.jsx
react-client-app/src/components/DataTbl.jsx
react-client-app/src/components/FieldsTbl.jsx
react-client-app/src/components/RulesTbl.jsx

Concepts and mapping rules now display a creation type

Display creation type

---

api/mapping/models.py
api/mapping/services.py
api/mapping/templates/mapping/scanreporttable_list.html
api/mapping/urls.py
api/mapping/views.py
api/requirements.txt
changelog.md
react-client-app/package.json
react-client-app/src/api/download.js
react-client-app/src/components/TablesTbl.jsx

Download Scan Report and Data Dictionary from Scan Report Table page. 
Data dictionary download button is disabled if no dd present for that scan report.

Download scan report

---

ProcessQueue/__init__.py
api/mapping/models.py
api/mapping/services_rules.py
changelog.md
react-client-app/src/App.jsx
react-client-app/src/components/DataTbl.jsx
react-client-app/src/components/FieldsTbl.jsx

Moved creation_type field from MappingRule to ScanreportConcept, and changed codebase to accomodate the change

Creation type model

---

.github/workflows/ci.yml

try setting `only-check` to 'no'.

allow black to edit, not just check

---

.github/workflows/ci.yml
NLPQueue/__init__.py
ProcessQueue/__init__.py
api/api/settings.py
api/data/models/concept.py
api/data/models/concept_relationship.py
api/domain/rules/engine.py
api/mapping/models.py
api/mapping/services_rules.py
api/mapping/views.py

Add `black` rule to `ci.yml` for code formatting on PR.

Add black action

---

api/mapping/models.py

This will need cherry-picking into devel afterwards.

Remove ScanReport as FK in DataDictionary.

---

react-client-app/src/App.jsx
react-client-app/src/api/values.js

* add procedure occurrence table
* fix #364

procedure occurrence table

---

api/mapping/serializers.py
api/mapping/urls.py
api/mapping/views.py

Added endpoints for project list, project filters, dataset list, and dataset filters

added new endpoints

---

api/mapping/forms.py
api/mapping/templates/mapping/upload_scan_report.html
api/mapping/views.py

- Remove Data Partner field from Scan Report form.
- Re-order form fields:
- Dataset
- Scan Report name
- WhiteRabbit ScanReport
- Data Dictionary

Rework sr upload form

---

react-client-app/src/components/Home.jsx
react-client-app/src/components/ScanReportTbl.jsx

Scan report list and home pages are now fixed but are slower from querying datasets by id 1 by 1, Need to add a new endpoint to be able to batch query them

React fixes

---

api/api/settings.py
api/mapping/test_permissions.py

- Add settings to allow Django to successfully build a test database
- Unit test for `CanViewProject` permission class

Set up unit testing

---

api/mapping/forms.py
api/mapping/templates/mapping/upload_scan_report.html
api/mapping/views.py

- Add visibility to SR upload form

Add visibility to form

---

ProcessQueue/__init__.py

Cherry-picks the contents of #391 for release to test branch

Cherry-pick sheet dimensions fix and mapping reuse bugfix to test branch

---

react-client-app/src/components/EditField.jsx
react-client-app/src/components/EditTable.jsx

- Correct `usePatch` request in `EditField.jsx` to not use now undefined variable to make URL.
- Correct `usePatch` request in `EditTable.jsx` to not use now undefined variable to make URL.

correct URLs for editing fields and tables

---

ProcessQueue/__init__.py
api/mapping/views.py

Also convert key to string in reuse_existing_field_concepts().
@dcl10 these are already in production as discussed yesterday; cherry-picking this here back to the devel branch.

Add missing filterset_field to ScanReportConceptFilterViewSet

---

react-client-app/src/api/values.js

It looks like I only did the procedure table and dreamt I did the specimen table 😢

Allow specimen table

---

api/mapping/templates/mapping/upload_scan_report.html
api/mapping/urls.py
api/mapping/views.py
react-client-app/src/App.jsx
react-client-app/src/api/values.js
react-client-app/src/components/UploadScanReport.jsx
react-client-app/src/uploadScanReport.jsx

Created the upload scanreport page in react

Upload scanreport react

---

react-client-app/src/components/ScanReportTbl.jsx

added name column to scanreport table

---

changelog.md
react-client-app/src/components/DataTbl.jsx
react-client-app/src/components/FieldsTbl.jsx
react-client-app/src/components/ScanReportTbl.jsx
react-client-app/src/components/TablesTbl.jsx

Values input fix

---

api/mapping/urls.py
api/mapping/views.py
changelog.md
react-client-app/src/components/UploadScanReport.jsx

Dataset now gets added to specified projects on creation

Scanreport upload

---

react-client-app/src/components/AnalysisTbl.jsx

* Changed header colours to differentiate ancestors/descendants 

Change header colour for Ancestors/Descendants

---

react-client-app/src/components/DataTbl.jsx
react-client-app/src/components/FieldsTbl.jsx

Added mapping rules button to fields page

added rules button to fields page and values page

---

react-client-app/src/components/DatasetAdminForm.jsx

fixed bug of being able to remove chips if not admin

fixed bug of being able to remove chips if not admin

---

api/mapping/views.py

Now adds the creating user as a dataset admin when a dataset is created through the datasets/create endpoint

Dataset creation

---

api/mapping/urls.py
react-client-app/src/components/DatasetAdminForm.jsx
react-client-app/src/components/ScanReportTbl.jsx

- Changed url of datasets admin to datasets details
- Changed Title to Details Page - Dataset # 127

Dataset details

---

api/mapping/views.py

* add missing cases to `DatasetListView`

add missing cases to `DatasetListView`

---

api/mapping/serializers.py

* change wrong test conditions on scan report validators

change wrong test conditions

---

api/mapping/templates/mapping/admin_dataset_form.html
api/mapping/views.py
react-client-app/src/components/ScanReportTbl.jsx
react-client-app/src/views/DatasetsContent.jsx

- Change "Added By" to "Author" in Scan Report List and Dataset Content page
- Fix link to Scan Report Details in Dataset Content page
- Change "Details" to "Dataset Details" in Dataset Content Page
- Change breadcrumb in Dataset Admin Form

Change button names, and fix links/breadcrumbs

---

api/mapping/serializers.py
api/mapping/views.py
changelog.md
react-client-app/src/components/UploadScanReport.jsx

- Added projects to dataset lists

Added projects to dataset lists

---

api/mapping/serializers.py
api/mapping/views.py
react-client-app/src/components/DatasetAdminForm.jsx

- Made users only show users in the datasets project(s) that are active and members of 1 of the projects
- Dataset inside co-connect

Dataset users

---

changelog.md
react-client-app/src/components/UploadScanReport.jsx

- Added current user as admin to new Dataset
- Changed name of 2 variables to be more accurate

Set creator as dataset admin

---

ProcessQueue/__init__.py
api/mapping/permissions.py
api/mapping/templates/mapping/error_404.html
api/mapping/templates/mapping/scanreportfield_form.html
api/mapping/templates/mapping/scanreportfield_list.html
api/mapping/templates/mapping/scanreporttable_form.html
api/mapping/templates/mapping/scanreporttable_list.html
api/mapping/templates/mapping/scanreportvalue_list.html
api/mapping/urls.py
api/mapping/views.py
changelog.md
react-client-app/src/App.jsx
react-client-app/src/api/download.js
react-client-app/src/api/values.js
react-client-app/src/components/EditField.jsx
react-client-app/src/components/EditTable.jsx
react-client-app/src/components/FieldsTbl.jsx
react-client-app/src/components/ScanReportTbl.jsx
react-client-app/src/components/TablesTbl.jsx
react-client-app/src/components/ValuesTbl.jsx
react-client-app/src/error404.jsx
react-client-app/src/views/DatasetsContent.jsx
react-client-app/src/views/Error404.jsx

- Can now view scanreport tables for a given scanreport at /scanreports/XXXX
-  Can now view fields for a given table at scanreports/XXX/tables/YYY
- Can now view values for a given field at scanreports/XXX/tables/YYY/fields/ZZZ
- Can now edit table at scanreports/XXX/tables/YYY/update
- Can now edit field at )scanreports/ZZZ/tables/XXX/fields/YYY/update
- created 404 page for when resources can't be found
- 404 page

Page refactors

---

changelog.md
react-client-app/src/views/DatasetTbl.jsx

- Added alert dialogue for when a user is unable to archive a dataset

Dataset archive

---

react-client-app/src/views/Error404.jsx

- fixed typo in an error message
NA

Fix typo in 404 message.

---

ProcessQueue/__init__.py
changelog.md

- Check if the scan reports in the active scan reports list belong to datasets that are not archived
- If dataset is active then keep scan report in active scan reports list

Add check for archived dataset

---

react-client-app/src/components/DatasetAdminForm.jsx
react-client-app/src/views/ScanReportAdminForm.jsx

- Add missing `Link` import to `DatasetAdminForm.jsx`
- Page now working

add missing `Link` import

---

README.md
react-client-app/src/components/UploadScanReport.jsx
react-client-app/src/views/ScanReportAdminForm.jsx

- Add info tooltips to upload page and SR admin page. NOTE I have not added to Dataset Admin page as this has not yet been refactored to use components.
- Also fixed two links to `scanreports` page.

Add info content

---

api/mapping/urls.py
api/mapping/views.py
react-client-app/src/components/ScanReportTbl.jsx

- Remove old views
- Fix create url

Remove old ListViews & correct ../create url

---

api/mapping/views.py

- added permission checks to sub-SR list pages

add permission checks

---

react-client-app/src/components/EditField.jsx

- Fix Redirect Link in Edit Field

Fix Edit Field Update redirect

---

api/mapping/views.py

Rename variable that shadowed one in the outer scope.
NA

Rename variable that shadowed one in the outer scope.

---

api/mapping/templates/mapping/error_404.html

- Changed the path of the 404 src import to work for all urls

changed path of 404 module

---

react-client-app/src/components/Home.jsx

- Changed URLs in home page to new urls

fixed urls

---

react-client-app/src/components/Home.jsx

- Set colours for current data partners. Any future ones will be set automatically using the hashed string

Change dashboard colours

---

api/mapping/views.py

- Added check on concepts creation for lists of concepts

added check on if it body is a list

---

api/mapping/views.py

Correct an else stmt which was associated to the wrong if.

---

api/mapping/templates/mapping/admin_dataset_form.html
api/mapping/templates/mapping/admin_scanreport_form.html
api/mapping/templates/mapping/dataset_list.html
api/mapping/templates/mapping/datasets_content.html
api/mapping/templates/mapping/home.html
api/mapping/templates/mapping/mappingrulesscanreport_list.html
api/mapping/templates/mapping/scanreport_list.html
api/mapping/templates/mapping/scanreportfield_form.html
api/mapping/templates/mapping/scanreportfield_list.html
api/mapping/templates/mapping/scanreporttable_form.html
api/mapping/templates/mapping/scanreporttable_list.html
api/mapping/templates/mapping/scanreportvalue_list.html
api/mapping/templates/mapping/upload_scan_report.html

-  Changed paths on html files for importing javascript files so that they support any url

changed src paths in html files

---

api/mapping/templates/mapping/mappingrulesscanreport_list.html

- Fixed s is not defined bug in mapping rules page

fixed bug caused by accidentally deleting a variable

---

changelog.md

Updated changelog to start v2.0.1

Update changelog.md to begin 2.0.1.

---

api/mapping/urls.py
api/mapping/views.py
react-client-app/src/components/DatasetAdminForm.jsx

- Added projects display to dataset admin form

added projects display to dataset admin form

---

react-client-app/src/components/CCMultiSelectInput.jsx
react-client-app/src/components/CCSelectInput.jsx
react-client-app/src/views/ScanReportAdminForm.jsx

- Fixed bug where page wouldn't load if the author is inactive
- When author is inactive you can't select them

Scanreport details inactive user

---

shared_code/omop_helpers.py

Add 2 further Runtime Warnings as guards on the output of api calls. This builds on the previous fix.

Add RuntimeWarnings to two later api call responses.

---

ProcessQueue/__init__.py

Fix a regression from #534 which might have caused a crash when long value names are supplied.
NA
NA

Truncate full_value in SRValue before POSTing.

---

changelog.md

Update changelog after 2.0.3 release.

---

changelog.md
react-client-app/src/components/FieldsTbl.jsx
react-client-app/src/components/ValuesTbl.jsx

Update the strings shown when loading fields and values tables, and when no fields or values are found.
NA

Update the strings shown when loading fields and values tables, and when no fields or values are found.

---

changelog.md

Update changelog with optional sheetnames.

---

ProcessQueue/__init__.py

Fix 2 regressions introduced by #534 
NA
NA

Fix upload bugs

---

ProcessQueue/__init__.py
changelog.md

Add changelog entries for 2.0.4 release candidate

Merge dev to test 2.0.4 changelog

---

changelog.md

Add v2.0.5-beta changelog section
NA
NA

Update changelog with new section.

---

ProcessQueue/__init__.py
changelog.md
react-client-app/src/api/values.js

Single bugfix release.
Paginates a GET request in values.js for ScanReportConcepts. This caused 400 errors when too many ScanReportConcepts were requested on a single Values page.

Merge dev to test 2.0.5

---

react-client-app/src/components/Home.jsx

Correct the headings in the 'Scan reports by status' table on the dashboard
NA
Previously:
Now: (TBC)

AB#63805 Correct the headings in the 'Scan reports by status' table on the dashboard

---

changelog.md

Add first 2.0.7-beta changelog entries

---

changelog.md

Finalise changelog for 2.0.7 rc

Finalise changelog for 2.0.7 release candidate.

---

api/mapping/services_rules.py

- Rewritten `get_mapping_rules_list()` function to greatly speed up the loading of the `/mapping_rules` page.
NA
NA

Speed up mapping rules page load

---

changelog.md

Finish changelog for 2.0.10.

---

.dockerignore
Dockerfile

- Rework Dockerfile to remove reinstall of nvm or npm or node dependencies unless they change. Also ignore node_modules directory, which bloats the image and slows down a chown command.
NA
NA

Speed up Docker rebuilds

---

react-client-app/src/App.jsx

Use React.lazy() and Suspense in App.jsx to use lazy loading across all pages.
NA

Use lazy loading

---

api/mapping/serializers.py
react-client-app/src/components/MappingTbl.jsx

- Re-add error handling in MappingTbl
- Remove unused python import.
NA
NA

Tidy up before 2.0.11

---

changelog.md
react-client-app/src/components/Home.jsx
react-client-app/src/components/ScanReportTbl.jsx

- Handle zero SRs gracefully on Home page and Scan Report list page.
NA
NA

Fix zero scanreport errors

---

react-client-app/src/components/Home.jsx

Fixed home page to handle the disabled counts correctly.

Fix disabled stats

---

app/api/mapping/services_rules.py
app/api/mapping/views.py
app/react-client-app/src/components/RulesTbl.jsx
changelog.md

This updates the csv export to sort columns in the right order, add the new required columns and rename the columns with more appropriate names. Resolves #650 
The frontend rules table has been updated as well for consistency.

650 CSV Export Update

---

.github/workflows/deploy.yml

Fixes using the correct way of getting secrets in the deployment pipeline.

Fix deployment secrets

---

app/api/mapping/services_rules.py

Changed csv export column from concept name to standard concept

Update csv export column from concept name to standard concept

---

.github/workflows/deploy.yml
app/api/api/settings.py
app/api/pyproject.toml
app/api/test/settings.py

Fixes a bug after updating to Django 4.2 in #640, a user could not log in to a deployed instance of the web app. 
Crucially a fix needed for Azure web apps:
https://stackoverflow.com/questions/66977121/azure-ad-redirect-uri-changes-from-https-to-http

Fix CSRF error on login

---

.zenodo.json

Adds a `.zenodo.json ` file to populate the fields of the zenodo DOI record in a controlled manner.

Add zenodo file for control of DOI information.

---

.github/workflows/deploy.yml

Adds Next.js deployments for test, and production. 
We have not activated either of the environments to be used yet, but this sets up the infrastructure and CD for them so we are ready once all issues are resolved.
Closes #694 
Closes #695

Add Nextjs deployments

---

app/api/proxy/urls.py
app/next-client-app/app/scanreports/[id]/columns.tsx
app/next-client-app/app/scanreports/[id]/page.tsx
app/next-client-app/components/data-table/index.tsx
app/next-client-app/components/scanreports/FacetsFilter.tsx
app/next-client-app/tailwind.config.ts
app/next-client-app/types/filter.ts

Next client fixes for deployment

---

app/next-client-app/app/custom.css

Fixes the header css, that I broke being too keen to delete css in #709

Fix header css

---

app/api/api/views.py
app/api/mapping/services_rules.py
app/react-client-app/src/components/RulesTbl.jsx

Fixes the summary view, as destination_field was needed to render.
And fixes the CSV export, as domain is access correctly.
Closes #690 
Closes #678

Fix rules serializing to views + CSV

---

app/next-client-app/app/scanreports/[id]/tables/[tableId]/fields/[fieldId]/page.tsx
app/next-client-app/app/scanreports/[id]/tables/[tableId]/page.tsx
app/next-client-app/app/scanreports/page.tsx
app/next-client-app/components/data-table/DataTablePagination.tsx
app/next-client-app/components/data-table/index.tsx

This PR added a "temporary" fix for the current server-side pagination issues. Please read the Notice in DataTablePagination.tsx component for more details
Closes #737 

Fix the pagination issue

---

app/api/pyproject.toml
changelog.md

Version bump for V2.2, preparing for a production release.

Release V2.2

---

app/api/api/views.py

A small fix to add `isAuthenticated` to some endpoints, a further fix will follow to clarify the permissions.

Add `isAuthenticated`

---

app/api/manage.py
app/api/poetry.lock
app/api/pyproject.toml

Adds Azure OpenTelemetry to Django - improving monitoring. 
Closes #782 

Add OpenTelemetry monitoring

---

app/api/proxy/urls.py
app/next-client-app/api/scanreports.ts
app/next-client-app/app/scanreports/[id]/tables/[tableId]/fields/[fieldId]/update/page.tsx
app/next-client-app/components/scanreports/ScanReportFieldEditForm.tsx
app/next-client-app/components/ui/checkbox.tsx
app/next-client-app/components/ui/textarea.tsx
app/next-client-app/package-lock.json
app/next-client-app/package.json

This PR implemented NextJS to build the page to view and update the details of a Scan report field.
Note: Tooltips couldn't be added due to the lack of information.
Closes #784 
General view

Implementation of NextJS to Edit Field view

---

app/api/api/views.py

Fix bug of missing method in ScanReportListViewSetV2

Bug fix for ScanReportListViewSetV2

---

app/api/api/urls.py
app/shared/poetry.lock
app/shared/pyproject.toml
app/shared/shared/files/paginations.py
app/shared/shared/files/serializers.py
app/shared/shared/files/service.py
app/shared/shared/files/views.py

Adds Files API endpoint for listing, and downloading a Scan Report mapping rules file.
There is a slight duplication of some existing code (e.g pagination, permissions) in the main api app, but as more logic moves to the shared apps this will be reduced. 
Closes #833 

Add files download API

---

app/next-client-app/app/(protected)/scanreports/[id]/mapping_rules/rules-buttons.tsx

Unfortunately in order to move mapping diagram serverless - we will have to containerise functions first.

Fixes viewing diagram

---

app/next-client-app/app/(protected)/scanreports/[id]/mapping_rules/rules-buttons.tsx

Reverts removal of the csv download...

Revert csv deletion

---

.github/workflows/deploy.production.yml
.github/workflows/deploy.yml

Fix deployment pipeline with hidden files.
Relevant: https://github.com/actions/upload-artifact/issues/602

Fix deployment pipeline

---

.github/workflows/ci.yml
.github/workflows/deploy.production.yml
.github/workflows/deploy.yml
.github/workflows/publish.yml
app/api/Dockerfile
app/api/entrypoint.sh

| |
|-|
🦋 Bug Fix
This PR moved the `entrypoint.sh` to `api` folder and fixed the workflow to deploy the Docker image of backend.
- Related Issue #933 
Deployed successfully to dev env.

Workflow Fixes

---

app/next-client-app/components/scanreports/ExportScanReport.tsx

| |
|-|
🦋 Bug Fix
The PR fixed and safeguarded the ScanReport name when users want to export a SR

Safeguarding ScanReport file exporting name

---

app/api/entrypoint.sh
app/shared/shared/mapping/management/commands/automatic_seeding_data.py
docker-compose.yml

#945 What does this PR do?
This PR introduces automatic data seeding for the database, ensuring that required tables and data are automatically populated when the application starts. The following changes were implemented:
- Added `automatic_seeding_data.py` to seed essential data into the database upon startup.
- Modified `entrypoint.sh` to execute the data seeding script during container startup.
- Utilised **Persistent Volume Storage for PostgreSQL** in `docker-compose.yml` to prevent data loss when restarting or bringing down containers.
**Why Persistent Volume Storage?**
Persistent Volume Storage was implemented for PostgreSQL in Docker to ensure that database data remains intact even after stopping or restarting the containers.
Without a persistent volume:
❌ Data is lost when …

Automatic-Seeding-Feature

---

app/next-client-app/components/core/menuItems.tsx

| |
|-|
🦋 Bug Fix
This PR fixed the link to the new docs site in the `mapper.carrot` webapp

Update docs link

---

docker-compose.yml

| |
|-|
🦋 Bug Fix
This PR added mounting for `shared` app into `api` service of the Docker compose stack. This helps the changes in `shared` can be reflected on Carrot in local dev.

Fix mounting for shared app in Docker Compose

---

docker-compose.yml

| |
|-|
🦋 Bug Fix
This PR fixed the mounting of the `shared` app to the `workers` app, making the code changes in the `shared` app to be applied and reflected automatically on `workers`'s Docker environment.
Closes #989

Fix mounting `shared` app to  `workers` app

---

.github/workflows/deploy.production.yml

♻️ Refactor - #1052 
This pull request updates the GitHub Actions production deployment workflow to use **UV instead of poetry** for dependency resolution and requirements file generation. 
- **Added:** Installation of uv and use of `uv pip compile pyproject.toml --output-file requirements.txt` to generate a pinned `requirements.txt` for deployment.
Feel free to share any feedback or suggestions for further improvements. Your input is always welcome! 🚀
Closes #1052

UV Compatible - Production Yaml

---

app/api/Dockerfile
app/api/entrypoint.sh

| |
|-|
🦋 Bug Fix
Fixes static files being able to be accessed after being built.
Closes #1059

Try dockerfile

---

.gitattributes

| |
|-|
🦋 Bug Fix
🛠️ Repo maintenance
This PR added the config to set mandatory LF line endings for .sh files

Fix entrypoint.sh line ending

---

app/airflow/dags/libs/SR_processing/core.py

| |
|-|
🦋 Bug Fix
Updating raw SQL query to match the recent DB migration.

Fix upload SR query

---

app/airflow/dags/libs/SR_processing/helpers.py

| |
|-|
🦋 Bug Fix
This PR is a hot fix for the Worksheet dimension was not calculated correctly.

fix wb dimension

---

app/next-client-app/app/(protected)/scanreports/[id]/actions-download-menu.tsx
app/next-client-app/app/(protected)/scanreports/[id]/layout.tsx
app/next-client-app/app/(protected)/scanreports/[id]/mapping_rules/rules-buttons.tsx
app/next-client-app/app/globals.css
app/next-client-app/components/scanreports/DeleteDialog.tsx
app/next-client-app/components/scanreports/ExportScanReport.tsx

♻️ Refactor
This PR removes duplication of action buttons, like request download rules only being shown on the view/review rule pages.
It has now been moved to the actions button.
Related #1076
Closes #1076

Completed Removing Duplicate actions button #1076

---

app/airflow/dags/SR_processing_dag.py
app/airflow/dags/auto_mapping_dag.py
app/airflow/dags/libs/auto_mapping/find_R_concepts_to_reuse.py
app/airflow/dags/libs/queries.py
app/airflow/dags/libs/settings.py
app/airflow/dags/rules_export_dag.py
docker-compose.yml

| |
|-|
♻️ Refactor
🦋 Bug Fix
This PR optimised the logic of finding matching values and fields for reusing. The functions will:
--> Find the eligible SR 
--> inside the SR table having the same name as the current SR table, find values with M concepts tied only (V concepts will now be handled completely by the other steps, and will not be reused) 
--> Add matching data 
--> find object ID based on matching data 
--> validate and create R concepts
The PR's goal is also to fix the function to find the matching values, which can take very long (sometimes forever) for a big SR field. Besides, it refactored the code/SQL for reusing functions and making the TIMEOUT of each DAGRUN configurable (defaulted to 60 mins)
Closes #1156

Refactor and fix finding matching value take forever

---

app/airflow/dags/libs/auto_mapping/find_R_concepts_to_reuse.py
app/airflow/dags/libs/queries.py

| |
|-|
🦋 Bug Fix
This PR separated the query of validating the concepts to be created as R concepts, making it more efficient and preventing hanging out.
This is a hot fix

Fix validating R concepts query

---

docker-compose.yml

| |
|-|
🛠️ Repo maintenance
Going along with https://github.com/Health-Informatics-UoN/carrot/pull/78, this PR cleaned up the Docker Compose file.
Airflow services are now on by default and can change the storage type flexibly.
Related https://github.com/Health-Informatics-UoN/carrot/pull/78

Clean up docker compose file

---

app/next-client-app/app/(protected)/scanreports/[id]/tables/[tableId]/fields/[fieldId]/beta/columns.tsx
app/next-client-app/constants/index.ts

| |
|-|
🦋 Bug Fix
Fixes the stored recommendations to be enabled in the frontend through an environment variable, enabling the feature to be default off.

Add `EnableStoredRecommendations`

---

.github/workflows/build-and-deploy-dev.yml
app/next-client-app/Dockerfile
app/next-client-app/next.config.js

| |
|-|
⚡️ Optimization
Reduces the build time from 16 minutes in CI, to 2-3 max, often <1 minute.
Related #
Closes #1208

Optimises the frontend container image

---

app/next-client-app/app/(protected)/scanreports/[id]/tables/[tableId]/fields/[fieldId]/beta/columns.tsx

| |
|-|
🦋 Bug Fix
Fix to make AI columns only appear if turned on.

Make AI columns optional
