- api/mapping/models.py
- api/mapping/templates/mapping/mapping_form.html
- api/mapping/templates/mapping/scanreportfield_list.html
- api/mapping/urls.py
- api/mapping/views.py
- docker/django/requirements.txt
Attempting to move the structural mapping edit form into it's own place (when you click the link 'Edit Structural Mapping'). 
I've got stuck at the final hurdle - as always it's with URL routing! I really can't work out how urls.py works with the templates and views we create. I think perhaps the code needs to be more verbose when using view classes? Can we consider using arguments in CBVs if they're available (rather than letting Django work behind the scenes)? 
For example:
```
class MyListView(ListView):
model = MyModel
template = "app/my_template.html"
```
Rather than:
```
class MyListView(ListView)
model = MyModel
...
<<Django magic happens here - how does the view route to our template?>>
...
```
Sometimes too much abstraction is a bad thing for understanding how the code works!
> 29519 structural mapping form

- api/static/style/custom.css
@py5gol this reverts the navbar color to be grey -- a grey consistent with the HDRIGateway palette 
Styles can be easily changed in the file `api/static/style/custom.css`
> revert navbar colors

- api/mapping/admin.py
- api/mapping/models.py
- api/mapping/services.py
- api/mapping/test_services.py
- api/mapping/views.py
This PR includes the code to import a data dictionary into the DataDictionary model. I am including this code as a PR so that we can keep it in master until required. We can develop this further as we refine our plan to upload and process data dictionaries. 
At the moment, this code **is not** called in `views.py` (i.e. if someone uploads a data dictionary using Vasiliki's document upload functionality, the data dictionary will not be processed and added to the DataDictionary model). 
If anyone would like to test how the data dictionary data is imported, you can run it via `test_services.py`:
`docker-compose exec api python manage.py test mapping.test_services.ServiceTests.test_import_data_dictionary`
You will need to upload your own data dictionary (in CSV format) to an appropriate …
> 31040 data dictionary parsing

- api/mapping/views.py
This PR:
Adds an order_by clause in the views.py method for scan report values so we avoid the re-ordering of the values after saving the concept_ids
> Fix concept_id re-order bug

- api/mapping/models.py
- api/mapping/views.py
This PR 
- uses the get_or_create method to check if a structural mapping already exists and if it does doesn't create it again.
- small change in models.py, where we define the STATUS_CHOICES so we have uniformity with OPERATION_CHOICES
- Default value for document model was changed to the STATUS_ARCHIVED so we have the correct default value
> If structural mapping already exists do not create again

- api/mapping/models.py
- api/mapping/templates/mapping/scanreportfield_list.html
- api/mapping/views.py
A new column was added to scan report field list that allows users to indicate whether they might want to pass the source value of the desired field as is into the mapping (e.g. age in years, height, weight, etc.)
> 31781 pass source value

- api/mapping/models.py
- api/mapping/templates/mapping/scanreportfield_list.html
- api/mapping/views.py
This PR:
- Adds concept_id as a field in ScanReportField model and sets the default value to be -1
- Allows the user to enter a concept_id for each column if needed and save the entry to the model
> Add conceptID in the ScanReportField model

- api/api/settings.py
- api/mapping/test_services.py
- docker/django/requirements.txt
This PR adds a lot of code to test_services.py
Calling `docker-compose exec api python manage.py test mapping.test_services.ServiceTests.test_get_omop` will run the test and output a pandas dataframe of cleaned results from the NLP service.
This update requires an update to coconnect tools submodule within /mapping-pipeline, so don't forget to `git pull origin master` within the co-connect-tools dir in the mapping-tools repo.
> test_services.py code to run NLP

- api/mapping/templates/mapping/mappingrulesscanreport_list.html
- api/mapping/templates/mapping/scanreporttable_list.html
Add .name to get the object name instead of the id in the templates
> fix names in table list and breadcrumb in mapping rules page

- docker/django/requirements.txt
django 3.1.8 is vulnerable 
https://dev.azure.com/UniversityOfNottingham/DRS/_backlogs/backlog/CO-CONNECT/Features/?workitem=36495
> [IMPORTANT] bump up django version

- .github/workflows/devel_ccom-func-dev.yml
to avoid the repeated failure to sync settings to kudu container. Revert setting of scm-do-build-during-deployment=true and enable-oryx-build=true.
> Pin Azure/functions-action to v1.3.2

- NLPQueue/function.json
- ProcessQueue/function.json
- api/mapping/services_nlp.py
- api/mapping/views.py
This PR has been raised to fix a number of (very) frustrating issues that @vpnu and I have been experiencing when developing Azure Functions code. Its purpose is to enable sending of queue messages to `<queue-name>-local` rather than the deployed queue (i.e. `nlpqueue` and `scanreports`) when developing locally. Without this change, AzFunc code is being triggered unintentionally and by different users when running Azure CLI locally, which is slowing down development considerably.
The environment variables are (for local development):
```
NLP_QUEUE_NAME=nlpqueue-local
SCAN_REPORT_QUEUE_NAME=scanreports-local
```
And for live:
```
NLP_QUEUE_NAME=nlpqueue
SCAN_REPORT_QUEUE_NAME=scanreports
```
For this PR to deploy successfully everywhere, env vars need to be maintained in the following …
> Env vars for Azure Functions queues

- .github/workflows/ci.yml
- .github/workflows/devel.yml
- Dockerfile.deploy
- README.md
Add `Dockerfile.deploy` which is used in deployment exactly as before. Repurpose `Dockerfile` to be used in a local development setting, mounting the `api` directory as a volume at container run time. This is documented in the `README.md`.
> Allow hot-reload and mount in local development

- api/requirements.txt
Removed markdown from requirements.txt
I can't see any places where it's called within the app, so I think this is the only trace of it!
> Removed markdown dependency

- entrypoint.sh
This is to stop the deployment failing because `staticfiles/` is not empty.
> set --noinput on collectstatic command

- api/mapping/serializers.py
- api/requirements.txt
Calum Mcdonald needs to extract only few fields from the scanreportvalues table for a specific scan report field using an API endpoint. 
This update will allow user to specify returning fields (instead of returning all fields) for the scanreportvalues of a given scan_report_field.  
The endpoint will look like this: http://localhost:8080/api/scanreportvaluesfilter/?scan_report_field=222&fields=value,frequency
> Shahzad api update july2021 specifying returning fields for scanreportvalues

- entrypoint.sh
to serve some of the longer requests which take longer than the default (30).
> Extend gunicorn timeout to 600 (10 minutes)

- api/mapping/serializers.py
- api/mapping/urls.py
- api/mapping/views.py
Addition of two new endpoints to extract all scanreportvalues for scan_report (requirement from Simon Tarr) and scan_report_table (requirement from Calum).  
1. Returning all scanreport values for a scan_report - http://localhost:8080/api/scanreportvaluesfilterscanreport/?scan_report=651
2. Returning all scanreport values for a scan_report_table - http://localhost:8080/api/scanreportvaluesfilterscanreporttable/?scan_report_table=8
> Shahzad - Extracting scanreport values for scan_report and scan_report_table

- api/mapping/serializers.py
This update will help users to specify returning fields for every endpoint in an API (except OMOP tables, if required this can be replicated to all those endpoints that deals with OMOP tables). In case if you don't supply returning fields parameter, it will return values of all fields. 
(API endpoints without filter)
API_URL/?fields=returningfield1,returningfield2 
(e.g. http://localhost:8080/api/scanreporttables/?fields=id,name  
and http://localhost:8080/api/scanreporttables/1/?fields=id,name)
(API endpoints with filter)
API_URL/?filterfield=value1&filterfield2=value2&fields=returningfield1,returningfield2 
(e.g. http://localhost:8080/api/scanreporttablesfilter/?scan_report=1&fields=id,name,person_id)
> Update Serializer.py to specify returning fields

- api/mapping/services_rules.py
Unknown problem with digraph when specifying the image size, we don't need to do this though and should auto scale in the svg element.
> fixing dag diagram issues

- api/mapping/models.py
This requires a migration when deployed to each system.
> Extend ScanReportField.name and .description_column to 512 chars.

- ProcessQueue/__init__.py
- changelog.md
Add `PAGE_MAX_CHARS` to ProcessQueue environment to flexibly change the max chars in a POST request.
> Page max chars in env

- api/mapping/serializers.py
- api/mapping/urls.py
- api/mapping/views.py
Samuel Adejumo is working on the scanreport page and this update will help him to extract user details for each scan report using API endppoints (as in each scan report we only store id of the user and user name and other information are usually stored in djanog user related table).
> Shahzad api updates retrieve user details

- api/mapping/models.py
Migrations have been applied to ccnetapptestdb to reflect status field in the scan report model. 
For each value pair the first is value (INPRO25) and second is label (In Progress (25%)).
> Update models.py to store Scan Report Status

- api/mapping/services_rules.py
Bug spotted by Erum in which mappings in the JSON were being overwritten because of the use of a dictionary structure
> make sure the id is unique for the rules json

- api/mapping/models.py
- api/mapping/views.py
Cherry pick the two commits `b555232` and `a822804` to remove `ScanReport` as a Foreign Key in the definition of `DataDictionary`.
These commits have previously been deployed to both test and prod systems.
> Cherry pick DD FK fix

- api/mapping/forms.py
- api/mapping/management/commands/unorphan_scanreports.py
- api/mapping/models.py
- api/mapping/permissions.py
- api/mapping/serializers.py
- api/mapping/templates/mapping/upload_scan_report.html
- api/mapping/urls.py
- api/mapping/views.py
- Alter `ScanReport` form to have a field for selecting a `parent_dataset`
- Change the form labels 
- from "Dataset name", corresponding to the `dataset` field in `ScanReport`, to "Scan Report name"
- "Dataset" denotes the `parent_dataset` field in `ScanReport`
- `ScanReportFormView` now adds the `parent_dataset` field to the `ScanReport` instance it creates
> Upload SR changes

- api/mapping/management/commands/add_datasets_to_partner.py
- api/mapping/management/commands/unorphan_scanreports.py
- api/mapping/models.py
- Add `data_partner` field to `Dataset`.
- `NULL` is allowed for now but once the production data is migrated, this can be disallowed. Datasets must be owned by a Data Partner.
- Created `add_datasets_to_partner` management command.
- Use to set datasets' data partners to that of the first scan report they contain, or to the one specified in the command line.
> Move datapartner to dataset

- api/mapping/models.py
- changelog.md
- Removed `data_partner` field from `ScanReport`
- Removed null constraint from `data_partner` field in `Dataset`
> Remove data partner from scan report

- api/mapping/models.py
- api/mapping/permissions.py
- api/mapping/test_permissions.py
- api/mapping/urls.py
- api/mapping/views.py
- changelog.md
Merge #382 into this branch before merging this PR.
- Add 2 visibility choices for Scan Reports and Datasets
- "Public" where a Scan Report or Dataset is available to users who are members of projects the Datasets and Scan Reports are in
- "Restricted" where a Scan Report or Dataset can only be seen by those in the `viewers` fields
- Added `visibility` field to `ScanReport` and `Dataset`
- Added `viewers` many-to-many field to `ScanReport` and `Dataset`. Links these to the `User` model
> Visibility and viewers

- ProcessQueue/__init__.py
Initially, this started out as
- Refactor the pagination code to enable a 2-dimensional pagination of two lists. This includes extracting the maximum characters for a GET request to a variable, removing the unused paginate_chars(), adding handle_max_chars() to reuse code, and changing the signature of paginate() as it no longer handles 2 lists.
However, the full PR goes further and applies some further refactoring and bug fixing.
> Refactor mapping reuse code

- react-client-app/package.json
- react-client-app/src/api/values.js
- Install `js-cookie 3.0.1`
- Extract CSRF token from cookies and send with `POST`/`PATCH` requests to fix 403 Forbidden bug introduced in #396
> add `X-CSRFToken` header to `usePatch` and `usePost`

- ProcessQueue/__init__.py
- changelog.md
This PR 
1.  Removes the 2-dimensional pagination code in favour of multiple calls to 1-dimensional pagination. This results in (a) fewer API calls; and (b) less code to maintain
2. Additionally removes all `print()` statements in `ProcessQueue` in favour of using the `logging` module. This defaults to only display the `INFO` level messages, but this can be changed to also show all `DEBUG` messages by simply modifying the `logger.setLevel` line.
> Remove 2 dimensional pagination and use `logging` module

- api/mapping/views.py
DataDictionary foreign key to scan_report was removed from the model, so removed the link to scan_report in ScanReportFormView where we create a data dictionary
> Fix DataDictionary creation to match new model

- api/mapping/permissions.py
- api/mapping/test_permissions.py
- api/mapping/test_views.py
- api/mapping/views.py
- Users with Dataset admin permission can view a dataset or scan report whether it is Public or Restricted
- User must be in `admins` field or the dataset
- User must be in the `admins` field of the scan report's `parent_dataset`
> View perms include admins

- api/mapping/services_rules.py
- Fixed broken downloading of mapping json and downloading of mapping csv caused by model changes
- The pull request fixes the bug caused by the migration changes, but I have found that download mapping csv for 
/scanreports/40/mapping_rules/
still throws an unrelated error.
I believe it is thrown on this line inside services_rules.py with this value inside the content variable
> fixed mapping json download

- api/mapping/templates/mapping/admin_dataset_form.html
- api/mapping/views.py
- react-client-app/src/components/ConceptTag.jsx
- react-client-app/src/components/DatasetAdminForm.jsx
- react-client-app/src/components/ScanReportTbl.jsx
- Edited the dataset admin page to show immutable values if the user is not an admin
- Added a link to the dataset admin page in the scanreport list page
If the user is not an admin, they will see this
Otherwise, they will see
> Dataset page

- .github/workflows/ci.yml
This is not totally desirable long-term, as we would be better to use releases. But the latest release still uses black 21.12, which is now broken. I've set a watch on the `black-check` repo so will be notified when that emits a new release we can directly reference.
NA
NA
> Update black to use `master`.

- api/mapping/views.py
- changelog.md
* Visibility not inherited from parent dataset. Default always to `PUBLIC`.
> do not inherit dataset visibility

- api/mapping/admin.py
- changelog.md
Made the django administration pages more responsive and more informative.
- More responsive through using `raw_id_field` on a number of `ForeignKey` and `ManyToMany` fields to stop all the possible objects being loaded for selection from dropdowns.
- More informative by displaying more columns on the changelist page of most classes: navigating is therefore easier because e.g. Projects are shown with their name rather than just their ID.
- Clearer selection of multiple users in the editor/admin/viewer fields by using the `filter_horizontal` option, and similarly when selecting datasets linked to a project.
None
`raw_id_fields`:
Changelist:
filter_horizontal:
> Reformat django admin pages

- api/mapping/views.py
- changelog.md
* Users without editor or admin permissions on an uploaded scan report's selected parent dataset cannot upload the scan report to that dataset.
> add check to SR upload form

- react-client-app/src/views/DatasetsContent.jsx
- Fixed bug where dataset page wouldn't load when there were no scanreports associated to them
- Used to result in permanent
- Now shows
> bug fix of dataset page not loading

- react-client-app/src/components/ScanReportTbl.jsx
- Fixed bug where archive hangs in loading if an error occurs. Now shows an error dialogue
> now show alert dialogue when archiving errors

- api/mapping/views.py
- react-client-app/src/App.jsx
- Added check on backend to make sure user can't add multiple concepts to the same object
- This is now shown when user tries to add a duplicate concept
> added check to stop duplicate concepts

- api/mapping/services_rules.py
- api/mapping/urls.py
- api/mapping/views.py
- react-client-app/src/components/AnalysisTbl.jsx
- react-client-app/src/components/EditField.jsx
- react-client-app/src/components/EditTable.jsx
- react-client-app/src/components/FieldsTbl.jsx
- react-client-app/src/components/MappingTbl.jsx
- react-client-app/src/components/RulesTbl.jsx
- react-client-app/src/components/SummaryTbl.jsx
- react-client-app/src/components/TablesTbl.jsx
- Fixed Source Table & Source Field links in Mapping Rules page, Summary View and Analysis View
- Deleted old Edit Table view
- Linked to new Edit Table view and fixed redirect on submit
- Deleted old Edit Field view
- Linked to new Edit Field and fixed redirect on submit
**Cannot remove these List views, new pages rely on them**
` path("scanreports/", views.ScanReportListView.as_view(), name="scan-report-list")`
`path("tables/", views.ScanReportTableListView.as_view(), name="tables") ` 
`path("fields/", views.ScanReportFieldListView.as_view(), name="fields")`
`path("values/", views.ScanReportValueListView.as_view(), name="values")`
_Removed all links pointing to tables/?search={id} or fields/?search={id}_
> Replace old urls

- react-client-app/src/components/MappingTbl.jsx
- Made buttons in mapping rules page responsive
> made mapping buttons responsive

- api/mapping/urls.py
- api/mapping/views.py
- react-client-app/src/components/DatasetAdminForm.jsx
- Added endpoint to count how many projects are on a dataset
- endpoint to get all projects on a specific dataset already existed
- Added check on if the editor can see all projects and warning on editing if they cannot
- Need to check if the existing endpoint that gets all projects in a specific dataset or if it only gets what the user is permitted to see
> Datasets admin projects endpoints

- api/mapping/views.py
- changed endpoint to only show projects that you are a member of. 
- Upload scanreport currently uses this endpoint to get all the projects in a dataset so that it can get all the members in all projects in a dataset which it uses to populate the select elements for viewers etc. This change may break that functionality as the user would only see members of projects that they can see
> changed endpoint to only show projects that you are a member of

- ProcessQueue/__init__.py
- ProcessQueue/blob_parser.py
- ProcessQueue/helpers.py
- api/mapping/test_views.py
- api/mapping/urls.py
- api/mapping/views.py
- changelog.md
This PR rewrites much of the ProcessQueue Azure Function, and introduces new endpoints to simplify the code. In particular, it
- rewrites the value/field reuse functions using new API endpoints which move significant portions of frontend code to the backend and in a much more concise form.
- splits out a number of the helper functions into two new files: `helpers.py` and `blob_parser.py`.
- reorders the definitions of a number of functions to clarify their relationships.
- fixes a bug where the contents of the final table was not uploaded in some circumstances.
- fixes a bug where empty cells in individual field sheets were creating None records.
> Clarify process queue

- ProcessQueue/__init__.py
- ProcessQueue/blob_parser.py
- shared_code/omop_helpers.py
- Fixed bug where a dict of dicts was incorrectly being created with a single dict as the interior object. This resulted in any fields with the same name ending up with the last vocab assigned to that name. So if 2 tables have the field "a" with different vocabs assigned to each, they'd both end up assigned to just the last such vocab as defined in the data dictionary. This is fixed by ensuring the interior dictionaries are separate instances, rather than a single instance.
- Also added logger to blob_parser.py and omop_helpers.py, 
- Shortened a couple of json calls.
NA
NA
> Fix bug where last vocab was being set for fields with the same name.

- api/mapping/services_rules.py
- changelog.md
- react-client-app/src/api/values.js
Add procedure_occurrence and specimen as allowed tables in services_rules.py. These had been missed when these tables had been added in `react-client-app/src/api/values.js`. This was manifesting in the following behaviour:
- Add a Concept from procedure_occurrence, e.g. "4015846 Quarantine" manually.
- Check the rules page, and this rule will be present.
- Click "Refresh rules", and notice that this rule disappears. This is because "Refresh Rules" removes the existing rules and rebuilds them from the Concepts registered. But with `procedure_occurrence` absent from the `m_allowed_tables` list, this rule failed and was not built.
Fix is to add `procedure_occurrence` and `specimen` to `m_allowed_tables`.
This PR also does a tiny bit of reformatting of white space.
NA
NA
**Important:** please …
> Add procedure_occurrence and specimen as allowed tables in services_rules.py

- ProcessQueue/__init__.py
Get available vocabs in ProcessQueue by querying the DB rather than hardcoded values. This means we can add further values just by updating the DB rather than having to redeploy code.
None
None
> Get available vocabs in ProcessQueue by querying the DB

- api/mapping/forms.py
- changelog.md
Raise errors earlier in the run_fast_consistency_checks() code to avoid unhelpful 500 error caused by running into a KeyError which had already been logged in errors but not yet raised.
Errors are raised earlier. This means not all errors get caught in a single pass, meaning users may have to fix one error, resubmit, and find more errors, but this is preferable to the current situation.
None
None
> Raise errors earlier in the run_fast_consistency_checks() code

- ProcessQueue/__init__.py
- ProcessQueue/helpers.py
- api/mapping/views.py
- changelog.md
- shared_code/omop_helpers.py
This PR rewrites the way vocabulary mapping is done in `ProcessQueue`. This requires a rewrite of a considerable chunk of code in order to enable batch processing and remove the need for PATCHing that was previously used.
It also now supports mapping a single non-standard concept to more than one standard concept.
None, though I need to check whether the additional vocabularies have been added to test and prod DBs.
NA
> SRValue upload rewrite

- api/mapping/forms.py
- Consistency checks which run on Scan Report file ignore the presence of sheets entitled "Table Overview" or "_". These are often present by default from WhiteRabbit output, but we do not use them in our uploads. To avoid the need for manually-curated SR files to include these, the code now ignores their presence. Of course, if you have a table in your dataset called "Table Overview" then this will break, but I expect WhiteRabbit might do something odd in that situation anyway.
NA
NA
> Make 'Table Overview' and '_' sheets optional

- react-client-app/src/api/values.js
Paginates a GET request in values.js for ScanReportConcepts. This caused 400 errors when too many ScanReportConcepts were requested on a single Values page.
NA
Previously:
Now:
> Paginate calls to mappingrulesfilter.

- api/mapping/views.py
- changelog.md
- react-client-app/src/api/values.js
Single bugfix release.
This PR removes an unnecessary call to mappingrulesfilter/, and adds concept as a filterset_field in that endpoint.
> Merge dev to test 2.0.6

- changelog.md
- react-client-app/src/components/FieldsTbl.jsx
- react-client-app/src/components/ValuesTbl.jsx
Add 'Edit Table', 'Scan Report Details' and 'Mapping Rules' buttons to top of Fields and Values pages
NA
> Add buttons to Field and Value pages

- api/templates/base.html
- changelog.md
Add dropdown to "Scan Reports" item in navbar. This makes the "New Scan Report" page accessible from all other pages.
NA
> Add 'New Scan Report Upload' in navbar dropdown.

- api/mapping/views.py
- changelog.md
- Remove get_context_data() from StructuralMappingTableListView, as it was unused and added a large overhead when calling get_mapping_rules_list().
NA
NA
> Remove get_context_data() from StructuralMappingTableListView

- changelog.md
- shared_code/omop_helpers.py
Remove duplicated ScanReportConcepts which are produced when non-standard codes are mapped via multiple routes to the same standard code.
NA
NA
> Remove duplicated ScanReportConcepts 

- react-client-app/src/views/DatasetTbl.jsx
Fix a bug where the archived filter was lost when loading from a URL on the Datasets page.
NA
NA
> Fix a bug where the archived filter was lost when loading from a URL.

- api/mapping/management/commands/refresh_mapping_rules.py
- api/mapping/services_rules.py
- changelog.md
- Added new management command `refresh_mapping_rules`.
- Bug fixed in `find_existing_scan_report_concepts()` which was causing some `SRConcepts` to be processed multiple times. This didn't cause any issues, but was misleading and wasteful.
NA
NA
> Add refresh_rules management command, and fix a bug

- api/mapping/views.py
- changelog.md
- Disable the stats counting in the right-hand columns of the ScanReport list page. These were causing problems, and taking 45s+ to return results, destabilising the whole platform. For now, these just return "Disabled" text instead. The functionality was always a convenience function, and would be better implemented with regularly scheduled recalculation rather than on-the-fly computation.
- Rework the filter for the SR list API call. This is a little easier to read and (potentially) more stream-lined.
NA
> Disable sr list stats

- README.md
- api/api/settings.py
- api/mapping/fixtures/mapping.json
- api/requirements.txt
- docker-compose.yml
- sample-env.txt
- sample-local.settings.json
Adds a developer quick start to get the app running, with corresponding documentation: https://github.com/HDRUK/CaRROT-Docs/pull/17
Includes:
- Adds a `docker-compose` to get the stack running.
- Updates the `sample-env` and `sample-local-settings` to use default values that work with the docker environment.
- Adds seed data fixtures to populate the `OmopTable` and `OmopField` tables.
- Adds python-dotenv as a dependency, to enable loading configuration from environment variables on all systems.
- Updates readme to point to the docs, it doesn't feel necessary to maintain both.
> Docs/135771 Add developer quickstart

- app/api/static/style/custom.css
- app/react-client-app/src/components/MappingTbl.jsx
- app/react-client-app/src/views/DatasetTbl.jsx
This changes the colour of the button indicating an active page, to blue so it is clearer to see. Resolves #606
> 606 Update pagination active page button colour

- app/react-client-app/src/views/DatasetTbl.jsx
This PR fixes which button should be active on the dataset view page depending on if it is active or archived datasets. Resolves #609
> 609 Update active dataset view

- app/api/mapping/serializers.py
- app/api/mapping/urls.py
- app/api/mapping/views.py
- app/react-client-app/src/api/values.js
- app/react-client-app/src/components/AnalysisTbl.jsx
- app/react-client-app/src/components/FieldsTbl.jsx
- app/react-client-app/src/components/ValuesTbl.jsx
- app/workers/CreateConcepts/__init__.py
- app/workers/CreateConcepts/reuse.py
- app/workers/shared_code/api.py
- app/workers/shared_code/helpers.py
- app/workers/test/CreateConcepts/test_create_concepts.py
- changelog.md
Fixes the hardcoded django `content_type` ids used in the backend, client, and workers.
This enables the app to be deployed fully working.
The approach has been to make the backend to be responsible for the `content_type`, and not trust the client, in two ways:
- When a `ScanReportConcept` is created through the API (when used by the workers, or the frontend), the content type is passed as a string, this is then used to lookup the content type ID.
- When a `content_type` is used for frontend logic, mostly for rendering / filtering, a new API endpoint has been created to get the content type ID.
Closes #637 
Closes #641 
Large diffs in the Javascript are Prettier working away.
> Fix magic numbers

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- app/workers/poetry.lock
- app/workers/pyproject.toml
- changelog.md
Updates the Azure Functions to use Python 3.11. 
We're having issues with having to build the functions in 3.9, but deploying in 3.8. So the quickest route is to use 3.11 for everything.
Relevant to: #640 
> Update Azure functions to Python 3.11

- app/workers/CreateConcepts/reuse.py
- app/workers/ProcessQueue/__init__.py
In #652 this updated the web API (amongst other things) to no longer use the hardcoded ids 15 / 17. 
But this broke the `ProcessQueue` function as it still uses them with the API. Although I'm expecting to delete this function soon, I'm keen to preserve it as a fallback option temporarily.
So this PR fixes the `ProcessQueue` to use the correct strings for the API.
> Fix ProcessQueue magic numbers

- .github/workflows/deploy.yml
- app/workers/shared_code/blob_parser.py
- changelog.md
Fixes a bug introduced in #643, and half fixed in #661. 
Currently when a data dictionary is not supplied with a Scan Report, the two functions mark this as a "None" string, or a None type. So we now safely catch for both cases.
At some point stronger typing will help prevent these! 
Also fixes the functions build from #671 
> Fix reusing Concepts without a data dictionary

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- app/api/mapping/services_rules.py
- app/api/mapping/views.py
- app/react-client-app/src/components/EditTable.jsx
- app/react-client-app/src/components/MappingTbl.jsx
- app/shared/.vscode/settings.json
- app/shared/poetry.lock
- app/shared/pyproject.toml
- app/shared/shared/services/__init__.py
- app/shared/shared/services/azurequeue.py
- app/shared/shared/services/rules.py
- app/shared/test/services/settings.py
- app/shared/test/services/test_azurequeue.py
- app/shared/test/services/test_rules.py
- app/workers/CreateConcepts/__init__.py
- app/workers/MappingRules/__init__.py
- app/workers/MappingRules/function.json
- app/workers/mapping/__init__.py
- app/workers/poetry.lock
- app/workers/pyproject.toml
- app/workers/shared_code/django_settings.py
- changelog.md
- sample-local.settings.json
Adds a new Azure Function `MappingRules`, that generates mapping rules when given a `table_id`.
The UX change is that reused mapping rules will now be generated when a user selects the Person Id and Date Event for that table, instead of using the "Refresh Rules" button.
This enables larger scan reports, as the workload is now serverless, and only happening on a table basis rather than a whole Scan Report. 
The UI has been updated with a notice to reflect this, and removing the "Refresh Rules" button entirely. The JSX changes are mostly Prettier working away.
The code to generate the rules is mostly lift and shift (added docs, types, tests), as we can now use the database directly in Azure functions.
I've moved this code into the shared package, with the intention of removing it from the …
> Add serverless mapping rules

- app/api/mapping/views.py
Deletes Django view query in `ScanReportListView`. The view fetches the data by API anyway, and this page is the most frequently used and takes too long to load. So at least removing one DB query will help a small bit, but also make it clearer that this is just not used.
Closes #685 
> Delete Django view queries

- app/api/api/urls.py
- app/api/api/views.py
- app/api/mapping/permissions.py
- app/next-client-app/api/scanreports.ts
- app/next-client-app/types/permissions.ts
Add a Permissions endpoint for a specific Scan Report - allowing the Next client to be able to access that users permissions for a Scan Report. 
This is purely to enable the Next client to optionally render depending on permissions.
> Add a Scan Report permissions API 

- app/api/api/paginations.py
- app/next-client-app/api/scanreports.ts
- app/next-client-app/app/scanreports/[id]/tables/[tableId]/update/page.tsx
- app/next-client-app/lib/api/utils.ts
Fixes the number of fields shown to the user, this was broken as pagination to this endpoint was added. 
Adds a API util that enables fetching all results from an endpoint - and implemented this for a Scan Reports Fields.
Closes #763 
> Fix update table list of columns limit

- .github/workflows/deploy.production.yml
- .github/workflows/deploy.yml
- app/api/templates/base.html
Updates the deployment workflow for dev, test, and production, to all take their application names from the environment variables, rather than hardcoded.
This enables us to deploy to the Carrot domain, related #734 
The problem is - we need to redirect the `azurewebsites.net` urls to `x.carrot.ac.uk`.
The plan:
> Update deployments workflow app-names

- app/next-client-app/next.config.js
Enables `allowedOrigins` to be an array, for example allowing for subdomains, as well as parents. `x.carrot.ac.uk` and `carrot.ac.uk`
Relates #734
> Add allowedOrigins to be an array

- app/api/api/filters.py
- app/api/api/router.py
- app/api/api/views.py
- app/api/poetry.lock
- app/api/pyproject.toml
Adds a permissions filter to Scan Reports, tables, fields, and values views. 
These permissions are based on the existing in `permissions.py`
Related #776 
> Add Scan Report permissions

- app/api/api/router.py
- app/api/api/views.py
- app/next-client-app/api/concepts.ts
- app/next-client-app/app/scanreports/[id]/layout.tsx
- app/next-client-app/app/scanreports/[id]/tables/[tableId]/fields/[fieldId]/page.tsx
- app/next-client-app/app/scanreports/[id]/tables/[tableId]/page.tsx
- app/next-client-app/components/concepts/add-concept.tsx
- app/next-client-app/components/core/Forbidden.tsx
Fixes fetching Scan Report Concepts at Scan Reports Fields/Values page level, to be conditional based on if fields/values exist. 
The issue was that if no fields/values existed, Concepts would still be fetched without the filtering, resulting in long running queries. A few of these in succession (for example, through revalidation) could slow the API down to a halt.
Additionally adding pagination to the endpoints used, and therefore updating the client to fetch all pages where necessary.
We will probably now upgrade any unpaginated endpoint to a `v2` with pagination, this is a general concern across every endpoint.
Additionally adds a Forbidden layout - if the user does not have permission to see the Scan Report.
Related #761 
> Fix fetching Concepts to be conditional

- app/api/api/serializers.py
- app/api/api/views.py
This PR adds a fix for the Adding Dataset. 
When modifying the API for Updating the Dataset details, changes there accidentally made the API for creating a new Data set break. This PR fixed it now by adding a V2 Serialiser. This will be combined in the future with the Adding New Dataset API, potentially.
> Adding dataset bug fix

- app/api/api/serializers.py
- app/api/api/views.py
- app/api/config/urls.py
- app/api/proxy/urls.py
- app/next-client-app/api/datasets.ts
- app/next-client-app/app/datasets/page.tsx
- app/next-client-app/app/scanreports/create/page.tsx
- app/next-client-app/components/Tooltips.tsx
- app/next-client-app/components/datasets/CreateDatasetDialog.tsx
- app/next-client-app/components/datasets/CreateDatasetForm.tsx
- app/next-client-app/components/form-components/FormikSelectDataset.tsx
- app/next-client-app/components/form-components/FormikSelectUsers.tsx
- app/next-client-app/components/scanreports/CreateScanReportForm.tsx
- app/next-client-app/components/ui/dialog.tsx
This PR added the ShadCN dialog to create a new dataset on the Create Scan Report and Dataset List pages.
Closes #774 
Closes #651 
- On the New Scan report page
- On the Dataset list page
> Add Create New Dataset Dialog

- app/next-client-app/components/datasets/CreateDatasetForm.tsx
- app/next-client-app/components/datasets/DatasetForm.tsx
This PR added the "Viewers" field for the dataset details and new dataset forms. This field, which wasn't made in previous PRs, will appear when users choose the RESTRICTED visibility mode, allowing users to add viewers to the dataset.
Closes #788 
> Add missing "viewers" field for dataset details and new dataset forms 

- app/api/api/views.py
- app/api/config/settings.py
- app/api/pyproject.toml
- app/next-client-app/app/scanreports/[id]/mapping_rules/get-file.tsx
- app/next-client-app/app/scanreports/[id]/mapping_rules/page.tsx
- app/react-client-app/src/components/MappingTbl.jsx
- changelog.md
- pyproject.toml
A couple of fixes for issues:
- Fixed added ordering where endpoints have been paginated - as these do not use the `DjangoFilterBackend` they need ordering on the queryset.
- Fix download json mapping rules in the Next UI
- Fix mapping diagram dialog size
- Removes the `Analyse Rules` button in the React app, discussed in #751 
- Make default login go to `/scanreports`
- Version bump to 2.2.9
> Fixes for pagination and others.

- app/api/api/views.py
- app/api/pyproject.toml
- app/entrypoint.sh
- changelog.md
- pyproject.toml
Add migrations to startup.
The three deployed instances of Carrot have been checked, and they are now consistent with the existing migrations in the repo. We can now make database changes in code.
Also removed cache on Scan Report tables - had unintended consequences as we don't have the infra to invalidate cache right now. 
> Add migrations

- app/api/api/apps.py
- app/api/api/filters.py
- app/api/api/signals.py
Fixes permissions filtering on Scan Report tables/fields/values
Adds clearing cache when permissions are updated.
> Fix cache clearing

- app/api/datasets/serializers.py
- app/api/projects/serializers.py
- app/api/projects/views.py
- app/next-client-app/api/datasets.ts
- app/next-client-app/app/(protected)/datasets/[id]/layout.tsx
- app/next-client-app/components/datasets/CreateDatasetDialog.tsx
- app/next-client-app/components/datasets/DatasetForm.tsx
- app/next-client-app/components/form-components/FormikSelectDataset.tsx
- app/next-client-app/components/form-components/FormikSelectEditors.tsx
- app/next-client-app/components/form-components/FormikSelectUsers.tsx
- app/next-client-app/types/dataset.ts
This PR added a fix for issue #835 where users can add a new dataset to a project they are not a member. Now, users can't see the project they are not in in the list of projects in the Add Dataset form or anywhere else.
Also, this PR improved the code for the dataset details section
Closes #835 
> Fix Adding dataset to projects where users don't have membership

- app/api/api/serializers.py
- app/next-client-app/app/(protected)/scanreports/[id]/downloads/page.tsx
- app/next-client-app/app/(protected)/scanreports/[id]/layout.tsx
- app/next-client-app/app/(protected)/scanreports/columns.tsx
- app/next-client-app/components/scanreports/ScanReportDetailsForm.tsx
- app/next-client-app/types/scanreport.ts
This PR adds the Author column to the ScanReport list page and SR details line.
Also, the Alert box on the Download page is now moved to the same line with the Columns button.
Closes #715 
> Add Author column to ScanReport list page

- app/api/api/views.py
- app/next-client-app/app/(protected)/scanreports/[id]/layout.tsx
- app/shared/shared/services/rules.py
This PR added a fix to the error when users can't add the new concept at the value level, which was caused by field datatype check in #881 
The supported data types of the SR field for the Observation table are updated in this PR as well.
Also, added a link to the breadcrumb section for SR.
> Fix error when add concept at value level

- app/next-client-app/components/concepts/concept-tags.tsx
- app/workers/RulesConceptsActivity/reuse.py
- app/workers/shared_code/db.py
This PR added a fix for the Carrot reuse vocabulary function which couldn't reuse multiple concepts added at the same Scan report field or value.
The fix focused on enabling Carrot to handle multiple existing concepts at both the field and value level of an SR.
This PR also added small gaps between concept tags
Closes #626 
<screenshot.jpg>
> Fix Carrot's reuse function

- app/workers/RulesConceptsActivity/__init__.py
This PR fixed the bug that made the "wrong" automatic mapping concepts built from OMOP. 
The cause of the bug is the original logic for updating "entries" would loop over the list of available concept relationships (which will be stripping out the duplicated concept relationship) --> only build the first concept correctly and wrongly for the rest if there are many same values in the same SR.
Thanks @AndyRae a lot 
Closes #778 
> Fix Carrot function of building vocabulary from OMOP

- app/api/api/views.py
- app/shared/shared/services/rules.py
- app/workers/poetry.lock
- app/workers/pyproject.toml
This PR added logic to support adding the "Meas Value" domain concepts. They will be mapped to the field "value_as_concept_id" of table MEASUREMENT in OMOP.
The filter for Review Rules was modified to avoid showing overlapping concepts on this page.
This PR was tested with the concepts in #769 and Carrot CDM. However, it may still need testing with the real SR and data
Closes #769 
Closes #648 (the concepts having "Meas value" will be mapped to the field "value_as_concept_id" of table MEASUREMENT following OMOP CDM 5.4 instructions - Noted: concepts having "Measurement" domain will not mapped to "value_as_concept_id", but the field "value_as_number" will be mapped as normal)
> Add support for concepts having "Meas value" domain

- app/workers/RulesConceptsActivity/__init__.py
This fix enables Carrot to automatically build multiple concepts from OMOP disabled by fix #890 which was assuming one vocab should only have one Non-standard to Standard map (OMOP) concept.
Closes #904
> Fix automated building multiple Vocabs concepts from OMOP

- app/entrypoint.sh
Removes the `npm run build` in the entrypoint.sh for running the webapp.
This is necessary to run the build for the legacy UI, but has begun to break in deployment.
So this is a hotfix, and maybe a temporary breaking change as it prevents running the CI. 
Relevant #761
> fix: Remove npm build in entrypoint

- app/api/api/serializers.py
This PR added validation for the size of a new Scan report when users want to upload it to Carrot. When the SR file is larger than `DATA_UPLOAD_MAX_MEMORY_SIZE` which defaults to 2.5 MB in Django, an error will appear on the top of the page.
Closes #901
> Add size validation for new Scan report

- docker-compose.yml
| |
|-|
🦋 Bug Fix
This PR fixed the NEXTAUTH_URL in Docker compose which should be http://localhost:3000/
> Fix NEXTAUTH_URL for Docker compose

- app/api/api/logger.py
- app/api/api/serializers.py
⚡️ Optimization #1003 
This PR implements **validation to check the Data Dictionaries' `csv_file_name` entries exactly match `Scan Report table names` (including file extensions)**. The changes prevent processing errors by catching mismatches during upload
- Added validation in ScanReportFilesSerializer to:
- Extract table names from Scan Report's "Table" column (including .csv extensions)
- Compare against Data Dictionary's `csv_file_name entries`
- Reject uploads with mismatched names
- Enhanced error messages that clearly show:
- Which table names are invalid
- Expected table names from the Scan Report
Feel free to share any feedback or suggestions for further improvements. Your input is always welcome! 🚀
Closes #1003
> Added validator for dd & sr

- app/workers/RulesConceptsActivity/__init__.py
- docker-compose.yml
🦋 Bug Fix - #1039 
This PR  fixes a bug that caused Carrot-Mapper's workers' function to crash in production. It prevents the creation of concepts with unsupported domains that would later fail in `RulesGenerationActivity`.
As a solution, we added an explicit **ALLOWED_DOMAINS** list check during concept creation and only created concepts from supported domains. I have added the screenshots and please find them below. 
I have already tested the scripts using the client's Data Dictionary & Scan Report (From Whales), which work well as expected. 
Feel free to share any feedback or suggestions for further improvements. Your input is always welcome! 🚀
Closes #1039
> Adding validator for Allowed Domains in RCA

- app/workers/RulesConceptsActivity/__init__.py
♻️ Refactor #1041
This PR ensures proper handling of non-standard OMOP concepts by:
- **Skipping unmapped concepts:** Non-standard concepts without valid "Maps to" relationships are now correctly excluded.
**Impact:** Prevents creation of invalid ScanReportConcept records for non-standard concepts without standard mappings.
I have tested the scripts using the client's Data Dictionary & Scan Report (From Whales), which work well as expected. 
Feel free to share any feedback or suggestions for further improvements. Your input is always welcome! 🚀
Closes #1041
> Upgraded - Concept Mapping Logic

- app/shared/shared/services/rules.py
- app/workers/RulesConceptsActivity/reuse.py
| |
|-|
🦋 Bug Fix
This PR add a small and hot fix for RulesConceptAct which keeps reusing the concepts that have the unsupported domains, ie., Visit or Specimen.
Related #1039
> Hot fix for rules generation

- .github/workflows/deploy.production.yml
- .github/workflows/deploy.yml
- app/airflow/dags/libs/auto_mapping/find_R_concepts_to_reuse.py
- app/next-client-app/app/layout.tsx
- app/next-client-app/components/scanreports/ScanReportTableUpdateForm.tsx
- app/next-client-app/next.config.js
- app/next-client-app/package-lock.json
- app/next-client-app/package.json
- docker-compose.yml
| |
|-|
🦋 Bug Fix
This PR fixed the env var populating configuration of the NextJS app:
- Env. var. which are used for client-side needs `NEXT_PUBLIC_` prefix and used the package `next-runtime-env` to populate. Otherwise, we will need to attach this throughthe  GH workflow
- Env. var. which are used for server-side needs to be populated through the GH workflow.
It also increases the limit for the NextJS body side to 20mb. (!%mb limit doesn't work for a DD with the size 12mb for some reason).
Besides, in Airflow, R concepts will be refreshed in both cases of `Trigger_reuse` is True or False.
Related #950
> Fix Environment variables config for Nextjs and set drop R concepts

- app/shared/shared/mapping/migrations/0007_alter_dataset_hidden_alter_mappingstatus_value_and_more.py
| |
|-|
🦋 Bug Fix
This PR removed the long-running indexes creation in the recent migration which causes the timeout on deployed instances of Carrot backend
Related #1106
> Remove time-consuming index creation in migration

- app/next-client-app/app/(protected)/scanreports/[id]/tables/[tableId]/update/page.tsx
🦋 Bug Fix
When users access the update table page for tables where Person ID and Date Event fields are not set, the Next.js client was making API calls with undefined field IDs, causing 404 errors and console warnings.
Added proper field existence checks before making API calls. Instead of blindly calling getScanReportField(id, tableId, table.person_id?.id), the code now checks if table.person_id?.id exists first. When fields don't exist, a default field object is used instead of making API calls with undefined values.
Related #1088
Closes #1088
> Fix undefined client request unavailable data

- app/next-client-app/app/(protected)/datasets/[id]/layout.tsx
✨ Feature
This PR makes project badges clickable in the dataset layout, allowing users to navigate directly to project pages from the dataset view. The badges now include hover effects and smooth transitions to provide clear visual feedback that they are interactive elements.
NB: The cursor on the screenshot isn't visible, but we can see `http://localhost:3000/projects/1` at the bottom left on hover.
Related #1071
Closes #1071
> Made Badge Clickable

- app/api/api/filters.py
- app/api/api/serializers.py
- app/api/api/urls.py
- app/api/api/views.py
- pyproject.toml
- uv.lock
| |
|-|
✨ Feature
Adds further backend to support server side rendering of the Scan Report Values / Concepts.
- Adds a filter to the `ScanReportValueListV3` that enables filtering by the type of Scan Report Concept (manual, vocab,  reused). 
- Adds a new Scan Report Concept detail API - which gives the full detail of a SR Concept, and its Concept
- Adds various new serializers to support this
Related #866
> Add server side values backend filtering, API

- app/next-client-app/app/(protected)/datasets/[id]/page.tsx
- app/next-client-app/app/(protected)/datasets/page.tsx
- app/next-client-app/app/(protected)/projects/[id]/page.tsx
- app/next-client-app/app/(protected)/projects/page.tsx
- app/next-client-app/app/(protected)/scanreports/page.tsx
- app/next-client-app/components/data-table/index.tsx
- app/next-client-app/components/recommendations/ai-suggestions-dialog.tsx
- app/next-client-app/components/ui/empty-state.tsx
⚡️ Optimization
Enhanced the DataTable component to show beautiful, contextual empty states instead of generic "No results" messages. Projects now display "Contact your administrator to be added to a project" with a folders icon, datasets show "Create your first dataset to start organizing and mapping your data" with a database icon, and scan reports guide users with "Create a dataset first to generate scan reports, or upload an existing scan report to begin mapping your data" with a filescan icon. Users now see helpful, contextual guidance instead of generic "No results" messages, creating a much better onboarding experience that directs them to the appropriate next steps with visually appealing and informative empty states.
Related #1171
Closes #1171
> Fix Empty state in lists
